services:
  phy_cache.client:
    class: '%phy_cache.class%'
    arguments: [ '%phy_cache.settings%' ]
  phy_cache:
    class: PHY\CacheBundle\Cache
    arguments: [ '@phy_cache.client' ]
    calls:
      - [ setExpiration, [ '%phy_cache.expiration%' ] ]
      - [ setCompression, [ '%phy_cache.compression%' ] ]
      - [ setPrefix, [ '%phy_cache.prefix%' ] ]